#version 130

// ArxModern "legacy" fragment shader: reproduces the fixed-function texture combiners
// (GL_COMBINE with GL_MODULATE / GL_REPLACE and RGB/alpha scale) and linear fog.
//
// Per stage, u_stageN = ivec2(colorOp, alphaOp) with the TextureStage::TextureOp values:
//   0 = disabled   : pass the previous stage through
//   1 = select     : texture
//   2 = modulate   : texture * previous
//   3 = modulate2x : texture * previous * 2
//   4 = modulate4x : texture * previous * 4
// A stage without a bound texture is reported as (0, 0).
//
// Per-pixel lighting, with the engine's own formula (scene/Light.cpp): Lambert term, constant
// up to fallstart, linear falloff to zero at fallend. u_lightPos = (xyz, fallstart),
// u_lightColor = (rgb, fallend), rgb premultiplied by intensity and the global light factor.
// - Level geometry (u_pixelLighting != 0): the vertex color carries the precomputed static
//   lighting and the first u_dynamicLightCount lights are added at half strength
//   (ApplyTileLights).
// - Entities (v_diffuse > 0): the vertex color carries the ambient term and all lights are
//   added, scaled by the diffuse factor (ApplyLight).
//
// Materials: the texture of stage 0 comes with a material map on unit 3 (u_normalMap). When
// generated by the engine (u_material.w != 0) it holds the tangent-space normal in rg, the
// height in b (parallax occlusion mapping) and the glossiness in a (Blinn-Phong specular of
// the lights); a <name>_n.* file supplied by a mod holds a plain rgb normal map.
// u_material = (parallax depth scale, gloss scale, metalness, generated flag).

#define MAX_LIGHTS 128

uniform sampler2D u_texture0;
uniform sampler2D u_texture1;
uniform sampler2D u_texture2;
uniform ivec2 u_stage0;
uniform ivec2 u_stage1;
uniform ivec2 u_stage2;

uniform int u_fogEnabled;
uniform vec3 u_fogColor;
uniform vec2 u_fogRange; // start, end

uniform int u_pixelLighting;
uniform int u_lightCount;
uniform int u_dynamicLightCount;
uniform vec4 u_lightPos[MAX_LIGHTS];
uniform vec4 u_lightColor[MAX_LIGHTS];
uniform vec3 u_cameraPos;

// Shadows: the first u_shadowCount dynamic lights have a cube map holding the distance
// from the light (normalised by fallend) of the nearest occluder in each direction.
uniform int u_shadowCount;
uniform samplerCube u_shadow0;
uniform samplerCube u_shadow1;
uniform samplerCube u_shadow2;
uniform samplerCube u_shadow3;

// Material map of the current material (texture unit 3), see u_normalMapped
uniform sampler2D u_normalMap;
uniform int u_normalMapped;
uniform float u_normalStrength;
uniform vec4 u_material;
uniform float u_specular; // global specular strength, 0 = off

// Soft particles: blended, depth-tested draws without depth write fade out where they get
// close to the opaque scene (u_depth = the scene depth on unit 8, captured before them).
// u_softMode: 0 = off, 1 = scale rgb (additive blends), 2 = scale alpha, 3 = towards white
// (multiplicative blends).
uniform int u_softMode;
uniform sampler2D u_depth;
uniform vec4 u_projection; // (proj[0][0], proj[1][1], Q, Q * near): view z = Q * near / (Q - z_ndc)
uniform vec2 u_invSize;

in vec4 v_color;
in vec2 v_texcoord0;
in vec2 v_texcoord1;
in vec2 v_texcoord2;
in float v_fogDistance;
in vec3 v_worldPos;
in vec3 v_normal;
in float v_diffuse;

#ifdef ARX_GBUFFER
// ArxModern traced lighting (post_trace.frag): the lit, opaque draws also leave what the
// lighting pass needs. The renderer only enables these outputs for them (GLPostProcess).
layout(location = 0) out vec4 fragColor;
layout(location = 1) out vec4 fragNormal; // world normal * 0.5 + 0.5, a = 1 (0 = nothing lit here)
layout(location = 2) out vec4 fragAlbedo; // the texture colour
layout(location = 3) out vec4 fragStatic; // the static part of the lighting (vertex colour, level lights)
#else
out vec4 fragColor;
#endif

// Tunables (a mod can edit this file: F7 reloads it)
const float ParallaxDepth = 0.018;    // uv units of relief at u_material.x == 1 (level geometry)
const float ParallaxRange = 900.0;    // world units beyond which the relief fades out
const float ParallaxEntity = 0.4;     // fraction of it on entities (their textures are atlases)
const int ParallaxSteps = 12;         // linear search steps of the parallax occlusion mapping
const float SoftDistance = 24.0;      // world units over which a particle fades against geometry
const float SpecularStrength = 0.9;   // overall specular scale
const float MinShininess = 12.0;      // Blinn-Phong exponent at gloss 0
const float MaxShininess = 220.0;     // ... and at gloss 1

vec3 combineColor(int op, vec3 tex, vec3 prev) {
	if(op == 1) {
		return tex;
	} else if(op == 2) {
		return min(tex * prev, 1.0);
	} else if(op == 3) {
		return min(tex * prev * 2.0, 1.0);
	} else if(op == 4) {
		return min(tex * prev * 4.0, 1.0);
	}
	return prev;
}

float combineAlpha(int op, float tex, float prev) {
	if(op == 1) {
		return tex;
	} else if(op == 2) {
		return min(tex * prev, 1.0);
	} else if(op == 3) {
		return min(tex * prev * 2.0, 1.0);
	} else if(op == 4) {
		return min(tex * prev * 4.0, 1.0);
	}
	return prev;
}

float shadowDistance(int i, vec3 dir) {
	if(i == 0) {
		return texture(u_shadow0, dir).r;
	} else if(i == 1) {
		return texture(u_shadow1, dir).r;
	} else if(i == 2) {
		return texture(u_shadow2, dir).r;
	}
	return texture(u_shadow3, dir).r;
}

// Fraction of the light reaching this fragment, with a small percentage-closer filter.
// fromLight = fragment - light position, dist = its length, fallend = light range,
// cosangle = cosine between the surface normal and the direction to the light.
float shadowFactor(int i, vec3 fromLight, float dist, float fallend, float cosangle) {
	const vec3 offsets[8] = vec3[8](
		vec3( 1.0,  1.0,  1.0), vec3( 1.0, -1.0,  1.0), vec3(-1.0, -1.0,  1.0), vec3(-1.0,  1.0,  1.0),
		vec3( 1.0,  1.0, -1.0), vec3( 1.0, -1.0, -1.0), vec3(-1.0, -1.0, -1.0), vec3(-1.0,  1.0, -1.0)
	);
	// Filter radius in world units, and the depth change it causes across a slanted surface
	float radius = dist * 0.006;
	float c = max(cosangle, 0.05);
	float slope = sqrt(1.0 - c * c) / c;
	float bias = (2.0 + radius * 1.8 * min(slope, 8.0)) / fallend;
	float current = dist / fallend;
	float lit = 0.0;
	for(int k = 0; k < 8; k++) {
		float stored = shadowDistance(i, fromLight + offsets[k] * radius);
		lit += (current - bias <= stored) ? 1.0 : 0.0;
	}
	return lit * (1.0 / 8.0);
}

// Tangent frame of the surface from the screen-space derivatives of the world position and
// texture coordinates (cotangent frame, C. Schüler), so no per-vertex tangents are needed.
// Returns false for a degenerate uv mapping.
bool tangentFrame(vec3 normal, out mat3 tbn) {
	vec3 dp1 = dFdx(v_worldPos);
	vec3 dp2 = dFdy(v_worldPos);
	vec2 duv1 = dFdx(v_texcoord0);
	vec2 duv2 = dFdy(v_texcoord0);
	vec3 dp2perp = cross(dp2, normal);
	vec3 dp1perp = cross(normal, dp1);
	vec3 tangent = dp2perp * duv1.x + dp1perp * duv2.x;
	vec3 bitangent = dp2perp * duv1.y + dp1perp * duv2.y;
	float invmax = inversesqrt(max(dot(tangent, tangent), dot(bitangent, bitangent)));
	if(invmax > 1e6) {
		return false;
	}
	tbn = mat3(tangent * invmax, bitangent * invmax, normal);
	return true;
}

// Parallax occlusion mapping: where the view ray enters the relief stored in the height
// channel of the material map. viewTS = direction towards the camera in tangent space.
vec2 parallaxUv(vec2 uv, vec3 viewTS, float depth) {
	if(depth <= 0.0 || viewTS.z <= 0.05) {
		return uv;
	}
	// Fewer layers head-on, more at grazing angles (where the offset is large)
	float layers = mix(float(ParallaxSteps), float(ParallaxSteps) * 2.0, 1.0 - viewTS.z);
	float layerDepth = 1.0 / layers;
	// Offset per layer: the ray goes down into the surface, away from the camera
	vec2 delta = -viewTS.xy / viewTS.z * depth * layerDepth;
	// Explicit gradients: derivatives are undefined inside the loop
	vec2 ddx = dFdx(uv);
	vec2 ddy = dFdy(uv);
	float currentDepth = 0.0;
	vec2 currentUv = uv;
	float surface = 1.0 - textureGrad(u_normalMap, currentUv, ddx, ddy).b;
	float previousSurface = surface;
	for(int i = 0; i < 2 * ParallaxSteps; i++) {
		if(currentDepth >= surface || float(i) >= layers) {
			break;
		}
		currentUv += delta;
		currentDepth += layerDepth;
		previousSurface = surface;
		surface = 1.0 - textureGrad(u_normalMap, currentUv, ddx, ddy).b;
	}
	// Interpolate between the last two layers where the ray crossed the surface
	float after = surface - currentDepth;
	float before = previousSurface - (currentDepth - layerDepth);
	float weight = after / (after - before + 1e-5);
	return mix(currentUv, currentUv - delta, clamp(weight, 0.0, 1.0));
}

#ifdef ARX_RT
// ArxModern RT (built with rt_common.glsl, "#define ARX_RT"): the shadows of the dynamic lights
// are traced through the level geometry, several rays per light towards a disc the size of
// the flame (soft edges). The cube maps then only hold the entities.
uniform int u_rtShadows;
uniform int u_rtDebug; // 1: show the traced shadow factor of the lights (post_debug=rtshadow)
const int ShadowRays = 4;        // traced rays per light and fragment in the penumbra
const float ShadowMinLight = 0.02; // lights contributing less than this are not traced
const float PenumbraRange = 900.0; // world units from the camera within which the penumbra is refined
const float LightRadius = 12.0;  // world units: size of the light source (penumbra width)

// Interleaved gradient noise (Jimenez 2014): rotates the sample pattern per pixel
float rtNoise(vec2 p) {
	return fract(52.9829189 * fract(0.06711056 * p.x + 0.00583715 * p.y));
}

// Rays from points spread over a disc (the light) to the fragment: the first two are opposite
// each other and settle most fragments (fully lit or fully in the umbra), the rest refine the
// penumbra. Traced from the light so that the back faces it may sit behind (a sconce, a log
// pile) are ignored (rt_common.glsl).
float tracedShadow(vec3 origin, vec3 lightPos, vec3 toLight, float cameraDistance) {
	vec3 up = (abs(toLight.y) < 0.9) ? vec3(0.0, 1.0, 0.0) : vec3(1.0, 0.0, 0.0);
	vec3 tx = normalize(cross(up, toLight));
	vec3 ty = cross(toLight, tx);
	float noise = rtNoise(gl_FragCoord.xy);
	// The penumbra detail is not worth it far away
	int rays = (cameraDistance < PenumbraRange) ? ShadowRays : 2;
	float lit = 0.0;
	for(int k = 0; k < rays; k++) {
		if(k == 2 && (lit == 0.0 || lit == 2.0)) {
			return lit * 0.5;
		}
		// Two opposite points at mid radius first, then a spiral over the disc (golden angle);
		// the whole pattern rotated per pixel
		float angle = noise * 6.2831853 + ((k < 2) ? float(k) * 3.14159265 : float(k) * 2.399963);
		float radius = LightRadius * ((k < 2) ? 0.7 : sqrt((float(k) + 0.5) / float(ShadowRays)));
		if(rtLit(lightPos + (tx * cos(angle) + ty * sin(angle)) * radius, origin)) {
			lit += 1.0;
		}
	}
	return lit / float(rays);
}
#endif

// Linear view depth of the scene behind this fragment (soft particles)
float sceneDepthAt(vec2 uv) {
	float zNdc = texture(u_depth, uv).r * 2.0 - 1.0;
	return u_projection.w / (u_projection.z - zNdc);
}

void main() {

	vec4 color = v_color;
	vec2 uv0 = v_texcoord0;
	// Gradients of the stage 0 coordinates, taken before any branch (parallax moves uv0)
	vec2 ddx0 = dFdx(v_texcoord0);
	vec2 ddy0 = dFdy(v_texcoord0);

	int lightCount = 0;
	float lightScale = 0.0;
	if(u_pixelLighting != 0) {
		lightCount = u_dynamicLightCount;
		lightScale = 0.5;
	} else if(v_diffuse > 0.0) {
		lightCount = u_lightCount;
		lightScale = v_diffuse;
	}

	vec3 specular = vec3(0.0);
	vec3 staticLight = color.rgb; // level: the precomputed vertex colour; entities: the ambient term
#ifdef ARX_RT
	float debugShadow = 1.0;
	vec3 debugBlocker = vec3(1.0);
#endif
	if(lightCount > 0) {
		vec3 normal = normalize(v_normal);
		vec3 geometric = normal;
		vec3 toCamera = u_cameraPos - v_worldPos;
		vec3 view = normalize(toCamera);
		float gloss = 0.0;
		mat3 tbn;
		if(u_normalMapped != 0 && tangentFrame(normal, tbn)) {
			if(u_material.w != 0.0) {
				// Generated map: relief in the height channel, gloss in the alpha channel
				float depth = ParallaxDepth * u_material.x * ((u_pixelLighting != 0) ? 1.0 : ParallaxEntity);
				// Only worth it up close, and toned down at grazing angles (the tangent frames of
				// neighbouring polygons differ, a large offset would show their seams)
				depth *= clamp(1.0 - length(toCamera) / ParallaxRange, 0.0, 1.0);
				vec3 viewTS = normalize(vec3(dot(toCamera, tbn[0]), dot(toCamera, tbn[1]), dot(toCamera, tbn[2])));
				depth *= smoothstep(0.0, 0.5, viewTS.z);
				uv0 = parallaxUv(uv0, viewTS, depth);
				vec4 material = textureGrad(u_normalMap, uv0, ddx0, ddy0);
				vec3 n = vec3(material.rg * 2.0 - 1.0, 0.0);
				n.z = sqrt(max(1.0 - dot(n.xy, n.xy), 0.0));
				n.xy *= u_normalStrength;
				normal = normalize(tbn * n);
				gloss = material.a * u_material.y;
			} else {
				vec3 n = texture(u_normalMap, uv0).xyz * 2.0 - 1.0;
				n.xy *= u_normalStrength;
				normal = normalize(tbn * n);
				gloss = u_material.y;
			}
		}
		float shininess = mix(MinShininess, MaxShininess, gloss);
		// Fresnel: brighter highlights at grazing angles
		float facing = max(dot(normal, view), 0.0);
		float fresnel = pow(1.0 - facing, 5.0);
		vec3 light = vec3(0.0);
		for(int i = 0; i < lightCount; i++) {
			vec3 toLight = u_lightPos[i].xyz - v_worldPos;
			float dist = length(toLight);
			float fallend = u_lightColor[i].w;
			if(dist >= fallend) {
				continue;
			}
			toLight /= dist;
			float cosangle = dot(normal, toLight);
			if(cosangle <= 0.0) {
				continue;
			}
			float fallstart = u_lightPos[i].w;
			float attenuation = (dist <= fallstart) ? 1.0 : (fallend - dist) / (fallend - fallstart);
#ifdef ARX_RT
			if(u_rtShadows != 0 && max(max(u_lightColor[i].r, u_lightColor[i].g), u_lightColor[i].b) * cosangle * attenuation * lightScale >= ShadowMinLight) {
				float traced = tracedShadow(v_worldPos + geometric * (1.0 + dist * 0.004), u_lightPos[i].xyz, toLight, length(toCamera));
				debugShadow = min(debugShadow, traced);
				if(u_rtDebug == 2) {
					// One ray from the light centre; the blocker's texture index as a colour
					if(!rtLit(u_lightPos[i].xyz, v_worldPos + geometric * (1.0 + dist * 0.004))) {
						debugBlocker = min(debugBlocker, vec3(float(i) / 8.0, 0.0, 0.0));
					}
				}
				attenuation *= traced;
				if(attenuation <= 0.0) {
					continue;
				}
			}
#endif
			if(i < u_shadowCount) {
				// Offset along the normal so that a surface does not shadow itself
				vec3 fromLight = (v_worldPos + normal * (2.0 + dist * 0.01)) - u_lightPos[i].xyz;
				attenuation *= shadowFactor(i, fromLight, length(fromLight), fallend, cosangle);
				if(attenuation <= 0.0) {
					continue;
				}
			}
			light += u_lightColor[i].rgb * (cosangle * attenuation);
			if(i >= u_dynamicLightCount) {
				staticLight += u_lightColor[i].rgb * (cosangle * attenuation * lightScale);
			}
			if(gloss > 0.0 && u_specular > 0.0) {
				vec3 halfway = normalize(toLight + view);
				float s = pow(max(dot(normal, halfway), 0.0), shininess) * (shininess + 8.0) * 0.02;
				specular += u_lightColor[i].rgb * (s * attenuation);
			}
		}
		color.rgb = min(color.rgb + light * lightScale, 1.0);
		specular *= gloss * SpecularStrength * u_specular * lightScale * 2.0 * (1.0 + 2.0 * fresnel);
	}

	vec3 albedo = vec3(1.0);
	if(u_stage0.x != 0 || u_stage0.y != 0) {
		vec4 tex = textureGrad(u_texture0, uv0, ddx0, ddy0);
		albedo = tex.rgb;
		color.rgb = combineColor(u_stage0.x, tex.rgb, color.rgb);
		color.a = combineAlpha(u_stage0.y, tex.a, color.a);
	}

	if(u_stage1.x != 0 || u_stage1.y != 0) {
		vec4 tex = texture(u_texture1, v_texcoord1);
		color.rgb = combineColor(u_stage1.x, tex.rgb, color.rgb);
		color.a = combineAlpha(u_stage1.y, tex.a, color.a);
	}

	if(u_stage2.x != 0 || u_stage2.y != 0) {
		vec4 tex = texture(u_texture2, v_texcoord2);
		color.rgb = combineColor(u_stage2.x, tex.rgb, color.rgb);
		color.a = combineAlpha(u_stage2.y, tex.a, color.a);
	}

	// Highlights: white on dielectrics, tinted by the surface on metals
	color.rgb += specular * mix(vec3(1.0), albedo, u_material.z);

	if(u_fogEnabled != 0) {
		// Linear fog, evaluated per fragment (the fixed-function result differs by a few
		// 8-bit steps in the distance, see README)
		float fog = clamp((u_fogRange.y - v_fogDistance) / (u_fogRange.y - u_fogRange.x), 0.0, 1.0);
		color.rgb = mix(u_fogColor, color.rgb, fog);
	}

	if(u_softMode != 0) {
		float sceneZ = sceneDepthAt(gl_FragCoord.xy * u_invSize);
		float fade = clamp((sceneZ - v_fogDistance) / SoftDistance, 0.0, 1.0);
		if(u_softMode == 1) {
			color.rgb *= fade;
		} else if(u_softMode == 2) {
			color.a *= fade;
		} else {
			color.rgb = mix(vec3(1.0), color.rgb, fade);
		}
	}

#ifdef ARX_RT
	if(u_rtDebug == 1) {
		color.rgb = vec3(debugShadow);
	} else if(u_rtDebug == 2) {
		color.rgb = debugBlocker;
		color.a = debugShadow;
	}
#endif

	fragColor = color;

#ifdef ARX_GBUFFER
	bool lit = (u_pixelLighting != 0) || (v_diffuse > 0.0);
	fragNormal = lit ? vec4(normalize(v_normal) * 0.5 + 0.5, 1.0) : vec4(0.0);
	fragAlbedo = vec4(lit ? albedo : vec3(0.0), 1.0);
	fragStatic = vec4(lit ? min(staticLight, 1.0) : vec3(0.0), 1.0);
#endif

}
