// Generated by tools/embed-shaders.py from data/graph/shaders - do not edit.
#ifndef ARX_GRAPHICS_OPENGL_GLSHADERSOURCES_H
#define ARX_GRAPHICS_OPENGL_GLSHADERSOURCES_H

namespace shadersources {

constexpr const char * legacy_frag = R"glsl(#version 130

// ArxModern "legacy" fragment shader: reproduces the fixed-function texture combiners
// (GL_COMBINE with GL_MODULATE / GL_REPLACE and RGB/alpha scale) and linear fog.
//
// Per stage, u_stageN = ivec2(colorOp, alphaOp) with the TextureStage::TextureOp values:
//   0 = disabled   : pass the previous stage through
//   1 = select     : texture
//   2 = modulate   : texture * previous
//   3 = modulate2x : texture * previous * 2
//   4 = modulate4x : texture * previous * 4
// A stage without a bound texture is reported as (0, 0).
//
// Per-pixel lighting, with the engine's own formula (scene/Light.cpp): Lambert term, constant
// up to fallstart, linear falloff to zero at fallend. u_lightPos = (xyz, fallstart),
// u_lightColor = (rgb, fallend), rgb premultiplied by intensity and the global light factor.
// - Level geometry (u_pixelLighting != 0): the vertex color carries the precomputed static
//   lighting and the first u_dynamicLightCount lights are added at half strength
//   (ApplyTileLights).
// - Entities (v_diffuse > 0): the vertex color carries the ambient term and all lights are
//   added, scaled by the diffuse factor (ApplyLight).

#define MAX_LIGHTS 128

uniform sampler2D u_texture0;
uniform sampler2D u_texture1;
uniform sampler2D u_texture2;
uniform ivec2 u_stage0;
uniform ivec2 u_stage1;
uniform ivec2 u_stage2;

uniform int u_fogEnabled;
uniform vec3 u_fogColor;
uniform vec2 u_fogRange; // start, end

uniform int u_pixelLighting;
uniform int u_lightCount;
uniform int u_dynamicLightCount;
uniform vec4 u_lightPos[MAX_LIGHTS];
uniform vec4 u_lightColor[MAX_LIGHTS];

// Shadows: the first u_shadowCount dynamic lights have a cube map holding the distance
// from the light (normalised by fallend) of the nearest occluder in each direction.
uniform int u_shadowCount;
uniform samplerCube u_shadow0;
uniform samplerCube u_shadow1;
uniform samplerCube u_shadow2;
uniform samplerCube u_shadow3;

// Normal map of the current material (tangent space, texture unit 3), see u_normalMapped
uniform sampler2D u_normalMap;
uniform int u_normalMapped;
uniform float u_normalStrength;

in vec4 v_color;
in vec2 v_texcoord0;
in vec2 v_texcoord1;
in vec2 v_texcoord2;
in float v_fogDistance;
in vec3 v_worldPos;
in vec3 v_normal;
in float v_diffuse;

out vec4 fragColor;

vec3 combineColor(int op, vec3 tex, vec3 prev) {
	if(op == 1) {
		return tex;
	} else if(op == 2) {
		return min(tex * prev, 1.0);
	} else if(op == 3) {
		return min(tex * prev * 2.0, 1.0);
	} else if(op == 4) {
		return min(tex * prev * 4.0, 1.0);
	}
	return prev;
}

float combineAlpha(int op, float tex, float prev) {
	if(op == 1) {
		return tex;
	} else if(op == 2) {
		return min(tex * prev, 1.0);
	} else if(op == 3) {
		return min(tex * prev * 2.0, 1.0);
	} else if(op == 4) {
		return min(tex * prev * 4.0, 1.0);
	}
	return prev;
}

float shadowDistance(int i, vec3 dir) {
	if(i == 0) {
		return texture(u_shadow0, dir).r;
	} else if(i == 1) {
		return texture(u_shadow1, dir).r;
	} else if(i == 2) {
		return texture(u_shadow2, dir).r;
	}
	return texture(u_shadow3, dir).r;
}

// Fraction of the light reaching this fragment, with a small percentage-closer filter.
// fromLight = fragment - light position, dist = its length, fallend = light range,
// cosangle = cosine between the surface normal and the direction to the light.
float shadowFactor(int i, vec3 fromLight, float dist, float fallend, float cosangle) {
	const vec3 offsets[8] = vec3[8](
		vec3( 1.0,  1.0,  1.0), vec3( 1.0, -1.0,  1.0), vec3(-1.0, -1.0,  1.0), vec3(-1.0,  1.0,  1.0),
		vec3( 1.0,  1.0, -1.0), vec3( 1.0, -1.0, -1.0), vec3(-1.0, -1.0, -1.0), vec3(-1.0,  1.0, -1.0)
	);
	// Filter radius in world units, and the depth change it causes across a slanted surface
	float radius = dist * 0.006;
	float c = max(cosangle, 0.05);
	float slope = sqrt(1.0 - c * c) / c;
	float bias = (2.0 + radius * 1.8 * min(slope, 8.0)) / fallend;
	float current = dist / fallend;
	float lit = 0.0;
	for(int k = 0; k < 8; k++) {
		float stored = shadowDistance(i, fromLight + offsets[k] * radius);
		lit += (current - bias <= stored) ? 1.0 : 0.0;
	}
	return lit * (1.0 / 8.0);
}

// Perturb the interpolated normal with the material's normal map. The tangent frame is
// built from the screen-space derivatives of the world position and texture coordinates
// (cotangent frame, C. Schüler), so no per-vertex tangents are needed.
vec3 perturbedNormal(vec3 normal) {
	if(u_normalMapped == 0) {
		return normal;
	}
	vec3 dp1 = dFdx(v_worldPos);
	vec3 dp2 = dFdy(v_worldPos);
	vec2 duv1 = dFdx(v_texcoord0);
	vec2 duv2 = dFdy(v_texcoord0);
	vec3 dp2perp = cross(dp2, normal);
	vec3 dp1perp = cross(normal, dp1);
	vec3 tangent = dp2perp * duv1.x + dp1perp * duv2.x;
	vec3 bitangent = dp2perp * duv1.y + dp1perp * duv2.y;
	float invmax = inversesqrt(max(dot(tangent, tangent), dot(bitangent, bitangent)));
	if(invmax > 1e6) {
		return normal; // degenerate uv mapping
	}
	mat3 tbn = mat3(tangent * invmax, bitangent * invmax, normal);
	vec3 n = texture(u_normalMap, v_texcoord0).xyz * 2.0 - 1.0;
	n.xy *= u_normalStrength;
	return normalize(tbn * n);
}

void main() {

	vec4 color = v_color;

	int lightCount = 0;
	float lightScale = 0.0;
	if(u_pixelLighting != 0) {
		lightCount = u_dynamicLightCount;
		lightScale = 0.5;
	} else if(v_diffuse > 0.0) {
		lightCount = u_lightCount;
		lightScale = v_diffuse;
	}
	if(lightCount > 0) {
		vec3 normal = perturbedNormal(normalize(v_normal));
		vec3 light = vec3(0.0);
		for(int i = 0; i < lightCount; i++) {
			vec3 toLight = u_lightPos[i].xyz - v_worldPos;
			float dist = length(toLight);
			float fallend = u_lightColor[i].w;
			if(dist >= fallend) {
				continue;
			}
			float cosangle = dot(normal, toLight / dist);
			if(cosangle <= 0.0) {
				continue;
			}
			float fallstart = u_lightPos[i].w;
			float attenuation = (dist <= fallstart) ? 1.0 : (fallend - dist) / (fallend - fallstart);
			if(i < u_shadowCount) {
				// Offset along the normal so that a surface does not shadow itself
				vec3 fromLight = (v_worldPos + normal * (2.0 + dist * 0.01)) - u_lightPos[i].xyz;
				attenuation *= shadowFactor(i, fromLight, length(fromLight), fallend, cosangle);
				if(attenuation <= 0.0) {
					continue;
				}
			}
			light += u_lightColor[i].rgb * (cosangle * attenuation);
		}
		color.rgb = min(color.rgb + light * lightScale, 1.0);
	}

	if(u_stage0.x != 0 || u_stage0.y != 0) {
		vec4 tex = texture(u_texture0, v_texcoord0);
		color.rgb = combineColor(u_stage0.x, tex.rgb, color.rgb);
		color.a = combineAlpha(u_stage0.y, tex.a, color.a);
	}

	if(u_stage1.x != 0 || u_stage1.y != 0) {
		vec4 tex = texture(u_texture1, v_texcoord1);
		color.rgb = combineColor(u_stage1.x, tex.rgb, color.rgb);
		color.a = combineAlpha(u_stage1.y, tex.a, color.a);
	}

	if(u_stage2.x != 0 || u_stage2.y != 0) {
		vec4 tex = texture(u_texture2, v_texcoord2);
		color.rgb = combineColor(u_stage2.x, tex.rgb, color.rgb);
		color.a = combineAlpha(u_stage2.y, tex.a, color.a);
	}

	if(u_fogEnabled != 0) {
		// Linear fog, evaluated per fragment (the fixed-function result differs by a few
		// 8-bit steps in the distance, see README)
		float fog = clamp((u_fogRange.y - v_fogDistance) / (u_fogRange.y - u_fogRange.x), 0.0, 1.0);
		color.rgb = mix(u_fogColor, color.rgb, fog);
	}

	fragColor = color;

}
)glsl";

constexpr const char * legacy_vert = R"glsl(#version 130

// ArxModern "legacy" vertex shader: reproduces the fixed-function transform.
//
// u_transform == 0 : vertices are pre-transformed (TexturedVertex, screen space with w),
//                    u_mvp maps pixels to clip space and the fog distance is the vertex w.
// u_transform == 1 : vertices are in world space, u_mvp = projection * view.

uniform mat4 u_mvp;
uniform mat4 u_view;
uniform int u_transform;

in vec4 a_position;
in vec4 a_color;
in vec2 a_texcoord0;
in vec2 a_texcoord1;
in vec2 a_texcoord2;
in vec4 a_normal;   // xyz = normal, w = diffuse factor (pre-transformed vertices only)
in vec3 a_worldPos; // pre-transformed vertices only

out vec4 v_color;
out vec2 v_texcoord0;
out vec2 v_texcoord1;
out vec2 v_texcoord2;
out float v_fogDistance;
out vec3 v_worldPos;
out vec3 v_normal;
out float v_diffuse;

void main() {

	gl_Position = u_mvp * a_position;

	v_color = a_color;
	v_texcoord0 = a_texcoord0;
	v_texcoord1 = a_texcoord1;
	v_texcoord2 = a_texcoord2;
	v_normal = a_normal.xyz;
	if(u_transform == 0) {
		v_worldPos = a_worldPos;
		v_diffuse = a_normal.w;
	} else {
		v_worldPos = a_position.xyz;
		v_diffuse = 0.0;
	}

	if(u_transform == 0) {
		// clip.w == view.z for pre-transformed vertices
		v_fogDistance = a_position.w;
	} else {
		// absolute eye-plane distance: the engine's view space looks down +z (D3D style),
		// and the fixed-function pipeline fogs with |z_eye| (GL_EYE_PLANE_ABSOLUTE_NV)
		v_fogDistance = abs((u_view * vec4(a_position.xyz, 1.0)).z);
	}

}
)glsl";

constexpr const char * post_vert = R"glsl(#version 130

// ArxModern post-processing: full-screen triangle generated from the vertex id, no attributes.

out vec2 v_uv;

void main() {
	vec2 p = vec2((gl_VertexID == 1) ? 3.0 : -1.0, (gl_VertexID == 2) ? 3.0 : -1.0);
	v_uv = p * 0.5 + 0.5;
	gl_Position = vec4(p, 0.0, 1.0);
}
)glsl";

constexpr const char * post_blur_frag = R"glsl(#version 130

// ArxModern bloom, pass 2: separable Gaussian blur; u_direction = (1/width, 0) or (0, 1/height).

uniform sampler2D u_source;
uniform vec2 u_direction;

in vec2 v_uv;
out vec4 fragColor;

void main() {
	const float weights[5] = float[5](0.227027, 0.1945946, 0.1216216, 0.054054, 0.016216);
	vec3 result = texture(u_source, v_uv).rgb * weights[0];
	for(int i = 1; i < 5; i++) {
		vec2 offset = u_direction * float(i);
		result += texture(u_source, v_uv + offset).rgb * weights[i];
		result += texture(u_source, v_uv - offset).rgb * weights[i];
	}
	fragColor = vec4(result, 1.0);
}
)glsl";

constexpr const char * post_extract_frag = R"glsl(#version 130

// ArxModern bloom, pass 1: keep what is brighter than the threshold (downsampled to half size).

uniform sampler2D u_scene;
uniform float u_threshold;

in vec2 v_uv;
out vec4 fragColor;

void main() {
	vec3 c = texture(u_scene, v_uv).rgb;
	float luma = dot(c, vec3(0.299, 0.587, 0.114));
	float amount = smoothstep(u_threshold, 1.0, luma);
	fragColor = vec4(c * amount, 1.0);
}
)glsl";

constexpr const char * post_final_frag = R"glsl(#version 130

// ArxModern post-processing, final pass: scene + bloom, then FXAA. Written to the window.
//
// u_bloom      : bloom intensity (0 disables)
// u_ao         : ambient occlusion strength (0 disables)
// u_fxaa       : 1 to enable the anti-aliasing filter
// u_invSize    : 1 / window size in pixels

uniform sampler2D u_scene;
uniform sampler2D u_bloomTexture;
uniform sampler2D u_aoTexture;
uniform float u_bloom;
uniform float u_ao;       // ambient occlusion strength (0 disables)
uniform int u_fxaa;
uniform vec2 u_invSize;
uniform int u_debug;      // 1 = show the ambient occlusion buffer, 2 = the bloom buffer

in vec2 v_uv;
out vec4 fragColor;

float luma(vec3 c) {
	return dot(c, vec3(0.299, 0.587, 0.114));
}

vec3 sceneAt(vec2 uv) {
	vec3 c = texture(u_scene, uv).rgb;
	if(u_ao > 0.0) {
		c *= mix(1.0, texture(u_aoTexture, uv).r, u_ao);
	}
	if(u_bloom > 0.0) {
		c += texture(u_bloomTexture, uv).rgb * u_bloom;
	}
	return c;
}

// Compact FXAA (after Timothy Lottes' FXAA 3.11, console/quality style)
vec3 fxaa(vec2 uv) {
	const float EDGE_THRESHOLD_MIN = 0.0312;
	const float EDGE_THRESHOLD_MAX = 0.125;
	const float SUBPIXEL_QUALITY = 0.75;
	const int ITERATIONS = 8;

	vec3 colorCenter = sceneAt(uv);
	float lumaCenter = luma(colorCenter);
	float lumaDown  = luma(sceneAt(uv + vec2(0.0, -u_invSize.y)));
	float lumaUp    = luma(sceneAt(uv + vec2(0.0,  u_invSize.y)));
	float lumaLeft  = luma(sceneAt(uv + vec2(-u_invSize.x, 0.0)));
	float lumaRight = luma(sceneAt(uv + vec2( u_invSize.x, 0.0)));

	float lumaMin = min(lumaCenter, min(min(lumaDown, lumaUp), min(lumaLeft, lumaRight)));
	float lumaMax = max(lumaCenter, max(max(lumaDown, lumaUp), max(lumaLeft, lumaRight)));
	float lumaRange = lumaMax - lumaMin;
	if(lumaRange < max(EDGE_THRESHOLD_MIN, lumaMax * EDGE_THRESHOLD_MAX)) {
		return colorCenter;
	}

	float lumaDownLeft  = luma(sceneAt(uv + vec2(-u_invSize.x, -u_invSize.y)));
	float lumaUpRight   = luma(sceneAt(uv + vec2( u_invSize.x,  u_invSize.y)));
	float lumaUpLeft    = luma(sceneAt(uv + vec2(-u_invSize.x,  u_invSize.y)));
	float lumaDownRight = luma(sceneAt(uv + vec2( u_invSize.x, -u_invSize.y)));

	float lumaDownUp = lumaDown + lumaUp;
	float lumaLeftRight = lumaLeft + lumaRight;
	float lumaLeftCorners = lumaDownLeft + lumaUpLeft;
	float lumaDownCorners = lumaDownLeft + lumaDownRight;
	float lumaRightCorners = lumaDownRight + lumaUpRight;
	float lumaUpCorners = lumaUpRight + lumaUpLeft;

	float edgeHorizontal = abs(-2.0 * lumaLeft + lumaLeftCorners) + abs(-2.0 * lumaCenter + lumaDownUp) * 2.0
	                     + abs(-2.0 * lumaRight + lumaRightCorners);
	float edgeVertical = abs(-2.0 * lumaUp + lumaUpCorners) + abs(-2.0 * lumaCenter + lumaLeftRight) * 2.0
	                   + abs(-2.0 * lumaDown + lumaDownCorners);
	bool isHorizontal = (edgeHorizontal >= edgeVertical);

	float luma1 = isHorizontal ? lumaDown : lumaLeft;
	float luma2 = isHorizontal ? lumaUp : lumaRight;
	float gradient1 = luma1 - lumaCenter;
	float gradient2 = luma2 - lumaCenter;
	bool is1Steepest = abs(gradient1) >= abs(gradient2);
	float gradientScaled = 0.25 * max(abs(gradient1), abs(gradient2));

	float stepLength = isHorizontal ? u_invSize.y : u_invSize.x;
	float lumaLocalAverage = 0.0;
	if(is1Steepest) {
		stepLength = -stepLength;
		lumaLocalAverage = 0.5 * (luma1 + lumaCenter);
	} else {
		lumaLocalAverage = 0.5 * (luma2 + lumaCenter);
	}

	vec2 currentUv = uv;
	if(isHorizontal) {
		currentUv.y += stepLength * 0.5;
	} else {
		currentUv.x += stepLength * 0.5;
	}

	vec2 offset = isHorizontal ? vec2(u_invSize.x, 0.0) : vec2(0.0, u_invSize.y);
	vec2 uv1 = currentUv - offset;
	vec2 uv2 = currentUv + offset;
	float lumaEnd1 = luma(sceneAt(uv1)) - lumaLocalAverage;
	float lumaEnd2 = luma(sceneAt(uv2)) - lumaLocalAverage;
	bool reached1 = abs(lumaEnd1) >= gradientScaled;
	bool reached2 = abs(lumaEnd2) >= gradientScaled;
	bool reachedBoth = reached1 && reached2;
	if(!reached1) {
		uv1 -= offset;
	}
	if(!reached2) {
		uv2 += offset;
	}

	if(!reachedBoth) {
		for(int i = 2; i < ITERATIONS; i++) {
			if(!reached1) {
				lumaEnd1 = luma(sceneAt(uv1)) - lumaLocalAverage;
			}
			if(!reached2) {
				lumaEnd2 = luma(sceneAt(uv2)) - lumaLocalAverage;
			}
			reached1 = abs(lumaEnd1) >= gradientScaled;
			reached2 = abs(lumaEnd2) >= gradientScaled;
			reachedBoth = reached1 && reached2;
			float quality = (i < 5) ? 1.5 : ((i < 7) ? 2.0 : 4.0);
			if(!reached1) {
				uv1 -= offset * quality;
			}
			if(!reached2) {
				uv2 += offset * quality;
			}
			if(reachedBoth) {
				break;
			}
		}
	}

	float distance1 = isHorizontal ? (uv.x - uv1.x) : (uv.y - uv1.y);
	float distance2 = isHorizontal ? (uv2.x - uv.x) : (uv2.y - uv.y);
	bool isDirection1 = distance1 < distance2;
	float distanceFinal = min(distance1, distance2);
	float edgeThickness = (distance1 + distance2);
	float pixelOffset = -distanceFinal / edgeThickness + 0.5;

	bool isLumaCenterSmaller = lumaCenter < lumaLocalAverage;
	bool correctVariation = ((isDirection1 ? lumaEnd1 : lumaEnd2) < 0.0) != isLumaCenterSmaller;
	float finalOffset = correctVariation ? pixelOffset : 0.0;

	float lumaAverage = (1.0 / 12.0) * (2.0 * (lumaDownUp + lumaLeftRight) + lumaLeftCorners + lumaRightCorners);
	float subPixelOffset1 = clamp(abs(lumaAverage - lumaCenter) / lumaRange, 0.0, 1.0);
	float subPixelOffset2 = (-2.0 * subPixelOffset1 + 3.0) * subPixelOffset1 * subPixelOffset1;
	float subPixelOffsetFinal = subPixelOffset2 * subPixelOffset2 * SUBPIXEL_QUALITY;
	finalOffset = max(finalOffset, subPixelOffsetFinal);

	vec2 finalUv = uv;
	if(isHorizontal) {
		finalUv.y += finalOffset * stepLength;
	} else {
		finalUv.x += finalOffset * stepLength;
	}
	return sceneAt(finalUv);
}

void main() {
	if(u_debug == 1) {
		fragColor = vec4(texture(u_aoTexture, v_uv).rrr, 1.0);
		return;
	} else if(u_debug == 2) {
		fragColor = vec4(texture(u_bloomTexture, v_uv).rgb, 1.0);
		return;
	}
	vec3 c = (u_fxaa != 0) ? fxaa(v_uv) : sceneAt(v_uv);
	fragColor = vec4(c, 1.0);
}
)glsl";

constexpr const char * post_ssao_frag = R"glsl(#version 130

// ArxModern screen-space ambient occlusion, computed at half resolution from the scene depth.
//
// The engine's projection (game/Camera.cpp) is D3D-style: z_clip = Q * z - Q * near, w_clip = z,
// so the linear view depth is  z = Q * near / (Q - z_ndc).
// u_projection = (proj[0][0], proj[1][1], Q, Q * near)

uniform sampler2D u_depth;
uniform vec4 u_projection;
uniform vec2 u_invSize;   // 1 / depth texture size
uniform float u_radius;   // world units
uniform float u_bias;     // world units

in vec2 v_uv;
out vec4 fragColor;

float linearDepth(vec2 uv) {
	float d = texture(u_depth, uv).r;
	float zNdc = d * 2.0 - 1.0;
	return u_projection.w / (u_projection.z - zNdc);
}

vec3 viewPosition(vec2 uv) {
	float z = linearDepth(uv);
	vec2 ndc = uv * 2.0 - 1.0;
	return vec3(ndc.x * z / u_projection.x, ndc.y * z / u_projection.y, z);
}

float hash(vec2 p) {
	return fract(sin(dot(p, vec2(12.9898, 78.233))) * 43758.5453);
}

void main() {

	vec3 position = viewPosition(v_uv);
	if(position.z >= 0.98 * (u_projection.w / (u_projection.z - 1.0))) {
		// far plane (background): no occlusion
		fragColor = vec4(1.0);
		return;
	}

	// Normal from the depth derivatives, picking the neighbour on each axis that is closest
	// in depth so that depth discontinuities (silhouettes) do not produce wrong normals
	vec3 right = viewPosition(v_uv + vec2(u_invSize.x, 0.0));
	vec3 left = viewPosition(v_uv - vec2(u_invSize.x, 0.0));
	vec3 up = viewPosition(v_uv + vec2(0.0, u_invSize.y));
	vec3 down = viewPosition(v_uv - vec2(0.0, u_invSize.y));
	vec3 dx = (abs(right.z - position.z) < abs(position.z - left.z)) ? (right - position) : (position - left);
	vec3 dy = (abs(up.z - position.z) < abs(position.z - down.z)) ? (up - position) : (position - down);
	vec3 normal = normalize(cross(dx, dy));
	if(dot(normal, -position) < 0.0) {
		normal = -normal;
	}

	// Random rotation around the normal
	float angle = hash(gl_FragCoord.xy) * 6.2831853;
	vec3 randomVec = vec3(cos(angle), sin(angle), 0.0);
	vec3 tangent = normalize(randomVec - normal * dot(randomVec, normal));
	vec3 bitangent = cross(normal, tangent);

	const int SAMPLES = 12;
	const vec3 kernel[12] = vec3[12](
		vec3( 0.2024,  0.8412, 0.4986), vec3(-0.2201, -0.1682, 0.5311), vec3( 0.1226,  0.0455, 0.1096),
		vec3(-0.0621,  0.2264, 0.2044), vec3( 0.6421, -0.0826, 0.4063), vec3(-0.3846, -0.4783, 0.3162),
		vec3( 0.0392, -0.1149, 0.0894), vec3(-0.7148,  0.2186, 0.3517), vec3( 0.2937,  0.3341, 0.1802),
		vec3(-0.1108, -0.0361, 0.0640), vec3( 0.5011, -0.6096, 0.2270), vec3(-0.3212,  0.0855, 0.0985)
	);

	float occlusion = 0.0;
	for(int i = 0; i < SAMPLES; i++) {
		vec3 k = kernel[i];
		vec3 samplePos = position + (tangent * k.x + bitangent * k.y + normal * k.z) * u_radius;
		if(samplePos.z <= 0.0) {
			continue;
		}
		// Project back to screen
		vec2 sampleUv = vec2(samplePos.x * u_projection.x / samplePos.z, samplePos.y * u_projection.y / samplePos.z) * 0.5 + 0.5;
		if(sampleUv.x < 0.0 || sampleUv.x > 1.0 || sampleUv.y < 0.0 || sampleUv.y > 1.0) {
			continue;
		}
		float sceneZ = linearDepth(sampleUv);
		float rangeCheck = smoothstep(0.0, 1.0, u_radius / abs(position.z - sceneZ));
		// Depth precision drops with distance: grow the bias with it
		float bias = u_bias + position.z * 0.004;
		occlusion += ((sceneZ <= samplePos.z - bias) ? 1.0 : 0.0) * rangeCheck;
	}

	float ao = 1.0 - occlusion / float(SAMPLES);
	fragColor = vec4(ao, ao, ao, 1.0);
}
)glsl";

constexpr const char * shadow_frag = R"glsl(#version 130

// ArxModern shadow map pass: stores the distance to the light, normalised by its range,
// in the red channel. The alpha channel carries the texture alpha so that the alpha test
// still cuts out grates and foliage.

uniform vec3 u_lightPos;
uniform float u_lightFallend;
uniform sampler2D u_texture0;
uniform int u_textured;
uniform int u_transform; // 0 = entity geometry, 1 = level geometry
uniform float u_lightOwner; // entity index carrying the light (-1 = none)

// The entity carrying a light never occludes it: a wall torch's bracket, a candle's stick, a
// character with a torch at the belt (the light sits inside its body) - and everything hanging
// from it (weapon, shield, the torch itself). Without this half the carrier would shadow the
// other half and the room, or a torch lit by a spell would give no light at all.
//
// Geometry this close to the light does not occlude it either. Entities: the hand casting a
// spell, an object standing right against a flame. Level: the engine places entity ignition
// lights 30 units above the flame, which for a wall torch under a beam or a low ceiling is
// inside the level geometry - without this the whole room would be in shadow.
const float ENTITY_NEAR = 30.0;
const float LEVEL_NEAR = 22.0;

in vec3 v_worldPos;
in vec2 v_texcoord0;
in float v_caster;

out vec4 fragColor;

void main() {
	if(u_transform == 0 && u_lightOwner >= 0.0 && abs(v_caster - u_lightOwner) < 0.5) {
		discard;
	}
	float alpha = (u_textured != 0) ? texture(u_texture0, v_texcoord0).a : 1.0;
	float worldDist = length(v_worldPos - u_lightPos);
	if(worldDist < ((u_transform == 0) ? ENTITY_NEAR : LEVEL_NEAR)) {
		discard;
	}
	fragColor = vec4(worldDist / u_lightFallend, 0.0, 0.0, alpha);
}
)glsl";

constexpr const char * shadow_vert = R"glsl(#version 130

// ArxModern shadow map pass: renders the distance to the light into one cube map face.
// u_transform == 0 : pre-transformed entity vertices, world position in a_worldPos
// u_transform == 1 : level geometry, world position in a_position

uniform mat4 u_lightViewProj;
uniform int u_transform;

in vec4 a_position;
in vec3 a_worldPos;
in vec2 a_texcoord0;
in float a_caster; // entity index of the vertex (entities only), -1 = none

out vec3 v_worldPos;
out vec2 v_texcoord0;
out float v_caster;

void main() {
	vec3 p = (u_transform == 0) ? a_worldPos : a_position.xyz;
	v_worldPos = p;
	v_texcoord0 = a_texcoord0;
	v_caster = a_caster;
	gl_Position = u_lightViewProj * vec4(p, 1.0);
}
)glsl";

constexpr const char * water_frag = R"glsl(#version 130

// ArxModern water surface.
//
// The engine draws water as a flat polygon with its own texture (already in the scene, with
// the floor below it showing through) and used to add three scrolling copies of the "enviro"
// highlight texture on top. This pass replaces that overlay: the scene behind the surface is
// read back through animated waves (refraction), the torches and other lights leave specular
// trails on the ripples, the water gets a little darker with depth, and the surface fades out
// against the banks instead of ending in a hard line.
//
// Inputs from the engine: u_scene / u_depth = the scene as rendered so far (resolved copies),
// u_enviro = the original highlight texture (unit 0) with its three scrolling uv sets,
// u_lightPos = (xyz, fallstart), u_lightColor = (rgb * intensity, fallend) as in legacy.frag.

#define MAX_LIGHTS 128

uniform sampler2D u_enviro;
uniform sampler2D u_scene;
uniform sampler2D u_depth;
uniform vec2 u_invSize;
uniform vec4 u_projection; // (proj[0][0], proj[1][1], Q, Q * near): view z = Q * near / (Q - z_ndc)
uniform vec3 u_cameraPos;
uniform float u_time;
uniform float u_strength; // 0..1, overall intensity of the effect
uniform int u_fogEnabled;
uniform vec2 u_fogRange;
uniform int u_lightCount;
uniform vec4 u_lightPos[MAX_LIGHTS];
uniform vec4 u_lightColor[MAX_LIGHTS];

in vec3 v_worldPos;
in float v_viewDepth;
in vec2 v_uv0;
in vec2 v_uv1;
in vec2 v_uv2;

out vec4 fragColor;

// Tunables (a mod can edit this file: F7 reloads it)
const float WaveHeight = 1.0;        // relative amplitude of the procedural waves
const float RippleDetail = 0.35;     // how much the enviro texture perturbs the normal
const float Refraction = 0.035;      // screen-space offset at full depth
const float RefractionDepth = 40.0;  // world units of water depth for full refraction
const float ShoreFade = 12.0;        // world units over which the surface fades at the banks
const float TintDepth = 250.0;       // world units of depth for full tint
const vec3 TintColor = vec3(0.55, 0.72, 0.85);
const float Specular = 1.2;
const float Shininess = 160.0;
const float LegacyMix = 0.2;         // how much of the original highlight overlay is kept

float linearDepth(float zBuffer) {
	float zNdc = zBuffer * 2.0 - 1.0;
	return u_projection.w / (u_projection.z - zNdc);
}

float sceneDepth(vec2 uv) {
	return linearDepth(texture(u_depth, uv).r);
}

// Sum of three plane waves: height and its slopes along two tangent directions
void waves(vec2 p, out float dhdu, out float dhdv) {
	dhdu = 0.0;
	dhdv = 0.0;
	// (direction, wavelength, speed, amplitude)
	vec2 d0 = normalize(vec2(1.0, 0.3));
	vec2 d1 = normalize(vec2(-0.4, 1.0));
	vec2 d2 = normalize(vec2(0.7, -0.8));
	float k0 = 6.2832 / 140.0, k1 = 6.2832 / 75.0, k2 = 6.2832 / 32.0;
	float a0 = 1.6, a1 = 0.9, a2 = 0.35;
	float ph0 = dot(d0, p) * k0 + u_time * 0.9;
	float ph1 = dot(d1, p) * k1 + u_time * 1.4;
	float ph2 = dot(d2, p) * k2 + u_time * 2.3;
	dhdu += a0 * k0 * cos(ph0) * d0.x + a1 * k1 * cos(ph1) * d1.x + a2 * k2 * cos(ph2) * d2.x;
	dhdv += a0 * k0 * cos(ph0) * d0.y + a1 * k1 * cos(ph1) * d1.y + a2 * k2 * cos(ph2) * d2.y;
	dhdu *= WaveHeight;
	dhdv *= WaveHeight;
}

void main() {

	// Geometric normal of the polygon (flat pools, but also waterfalls), facing the camera
	vec3 dpdx = dFdx(v_worldPos);
	vec3 dpdy = dFdy(v_worldPos);
	vec3 geoNormal = normalize(cross(dpdx, dpdy));
	vec3 toCamera = u_cameraPos - v_worldPos;
	float toCameraLength = length(toCamera);
	vec3 view = toCamera / max(toCameraLength, 0.001);
	if(dot(geoNormal, view) < 0.0) {
		geoNormal = -geoNormal;
	}

	// Tangent frame on the surface and the perturbed normal
	vec3 tangent = normalize(abs(geoNormal.y) > 0.9 ? cross(geoNormal, vec3(1.0, 0.0, 0.0)) : cross(geoNormal, vec3(0.0, 1.0, 0.0)));
	vec3 bitangent = cross(geoNormal, tangent);
	vec2 surfacePos = vec2(dot(v_worldPos, tangent), dot(v_worldPos, bitangent));
	float dhdu, dhdv;
	waves(surfacePos, dhdu, dhdv);
	vec2 ripple = (texture(u_enviro, v_uv1).rg - texture(u_enviro, v_uv2).gb) * RippleDetail;
	vec3 normal = normalize(geoNormal - tangent * (dhdu * u_strength + ripple.x) - bitangent * (dhdv * u_strength + ripple.y));

	// Scene behind the surface, refracted where the water is deep enough
	vec2 uv = gl_FragCoord.xy * u_invSize;
	float surfaceZ = linearDepth(gl_FragCoord.z);
	float thickness = max(sceneDepth(uv) - surfaceZ, 0.0);
	vec2 offsetDir = vec2(dot(normal - geoNormal, tangent), dot(normal - geoNormal, bitangent));
	vec2 offset = offsetDir * Refraction * u_strength * clamp(thickness / RefractionDepth, 0.0, 1.0);
	vec2 uv2 = clamp(uv + offset, u_invSize, 1.0 - u_invSize);
	float sceneZ2 = sceneDepth(uv2);
	if(sceneZ2 < surfaceZ) {
		// Something stands between the camera and the water there: no refraction across it
		uv2 = uv;
		sceneZ2 = sceneDepth(uv);
	}
	vec3 scene = texture(u_scene, uv2).rgb;
	float depth2 = max(sceneZ2 - surfaceZ, 0.0);

	// The original overlay, toned down: three scrolling highlight layers modulated together
	vec3 overlay = texture(u_enviro, v_uv0).rgb * texture(u_enviro, v_uv1).rgb * 4.0 * texture(u_enviro, v_uv2).rgb * 0.314;
	vec3 color = scene * (1.0 + overlay * LegacyMix) + overlay * LegacyMix * 0.25;

	// A little darker and bluer with depth
	float tint = clamp(depth2 / TintDepth, 0.0, 1.0) * u_strength;
	color *= mix(vec3(1.0), TintColor, tint);

	// Fresnel: glossier at grazing angles
	float facing = max(dot(normal, view), 0.0);
	float fresnel = 0.03 + 0.97 * pow(1.0 - facing, 5.0);

	// Specular trails of the scene's lights (same attenuation as the engine)
	vec3 specular = vec3(0.0);
	for(int i = 0; i < u_lightCount; i++) {
		vec3 toLight = u_lightPos[i].xyz - v_worldPos;
		float dist = length(toLight);
		float fallend = u_lightColor[i].w;
		if(dist >= fallend) {
			continue;
		}
		float fallstart = u_lightPos[i].w;
		float attenuation = (dist <= fallstart) ? 1.0 : (fallend - dist) / (fallend - fallstart);
		vec3 halfway = normalize(toLight / dist + view);
		float s = pow(max(dot(normal, halfway), 0.0), Shininess);
		specular += u_lightColor[i].rgb * (s * attenuation);
	}
	color += specular * (Specular * u_strength * (0.4 + 0.6 * fresnel));

	// Fog dims the highlights as it does the scene
	if(u_fogEnabled != 0) {
		float fog = clamp((u_fogRange.y - v_viewDepth) / (u_fogRange.y - u_fogRange.x), 0.0, 1.0);
		color = mix(scene, color, fog);
	}

	// Fade against the banks and anything standing in the water
	float shore = clamp(thickness / ShoreFade, 0.0, 1.0);
	color = mix(texture(u_scene, uv).rgb, color, shore);

	fragColor = vec4(color, 1.0);
}
)glsl";

constexpr const char * water_vert = R"glsl(#version 130

// ArxModern water surface: the water polygons of the level (world space), drawn after the
// scene with the scene colour and depth available to the fragment shader.

uniform mat4 u_viewProj;
uniform mat4 u_view;

in vec4 a_position;
in vec4 a_color;
in vec2 a_texcoord0;
in vec2 a_texcoord1;
in vec2 a_texcoord2;

out vec3 v_worldPos;
out float v_viewDepth;
out vec2 v_uv0;
out vec2 v_uv1;
out vec2 v_uv2;

void main() {
	v_worldPos = a_position.xyz;
	v_viewDepth = abs((u_view * vec4(a_position.xyz, 1.0)).z);
	v_uv0 = a_texcoord0;
	v_uv1 = a_texcoord1;
	v_uv2 = a_texcoord2;
	gl_Position = u_viewProj * vec4(a_position.xyz, 1.0);
}
)glsl";

} // namespace shadersources

#endif // ARX_GRAPHICS_OPENGL_GLSHADERSOURCES_H
